name: BEDOPS CI

on: [push, pull_request]

jobs:

  build:

    name: Build and test BEDOPS suite

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os : [ubuntu-16.04, macos-10.15]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ubuntu-specific setup
        if: matrix.os == 'ubuntu-16.04'
        run: |
          sudo apt-get install -qq gcc-4.8 g++-4.8
          sudo update-alternatives \
            --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 100
          sudo update-alternatives \
            --install /usr/bin/g++ g++ /usr/bin/g++-4.8 100

      - name: Mac OS X-specific setup
        if: matrix.os == 'macos-10.15'
        env:
          CC: clang
          GCC: clang++
          KERNEL: Darwin
        run: |
          env

      - name: Build binaries
        run: make all

      - name: Install binaries
        run: make install_all

      - name: Test binaries
        run: make tests
