name: Bedops CI

on: [push, pull_request]

jobs:
  
  build:

    name: Build all bedops binaries

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os : [ubuntu-16.04]

    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Setup dependencies
        if: matrix.os == 'ubuntu-16.04'
        run: |
          sudo apt-get install -qq gcc-4.8 g++-4.8
          sudo update-alternatives \
            --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 100
          sudo update-alternatives \
            --install /usr/bin/g++ g++ /usr/bin/g++-4.8 100

      - name: make all
        run: make all

      - name: make install_all
        run: make install_all
